# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Item" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :completed, :bool, 3
  end
  add_message "ListItemsRequest" do
  end
  add_message "AddItemRequest" do
    optional :name, :string, 1
  end
  add_message "RemoveItemRequest" do
    optional :id, :string, 1
  end
  add_message "ToggleItemRequest" do
    optional :id, :string, 1
  end
  add_message "ItemAdded" do
    optional :id, :string, 1
  end
  add_message "ItemRemoved" do
  end
  add_message "ItemToggled" do
  end
end

Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("Item").msgclass
ListItemsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListItemsRequest").msgclass
AddItemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("AddItemRequest").msgclass
RemoveItemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveItemRequest").msgclass
ToggleItemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ToggleItemRequest").msgclass
ItemAdded = Google::Protobuf::DescriptorPool.generated_pool.lookup("ItemAdded").msgclass
ItemRemoved = Google::Protobuf::DescriptorPool.generated_pool.lookup("ItemRemoved").msgclass
ItemToggled = Google::Protobuf::DescriptorPool.generated_pool.lookup("ItemToggled").msgclass
