# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo.proto for package ''

require 'grpc'
require 'todo_pb'

module Todo
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Todo'

    rpc :AddItem, AddItemRequest, ItemAdded
    rpc :RemoveItem, RemoveItemRequest, ItemRemoved
    rpc :ToggleItem, ToggleItemRequest, ItemToggled
    rpc :ListItems, ListItemsRequest, stream(Item)
  end

  Stub = Service.rpc_stub_class
end
