# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "SayHello" do
    optional :name, :string, 1
  end
  add_message "Hello" do
    optional :message, :string, 1
  end
end

SayHello = Google::Protobuf::DescriptorPool.generated_pool.lookup("SayHello").msgclass
Hello = Google::Protobuf::DescriptorPool.generated_pool.lookup("Hello").msgclass
